Adding arm64 and buildx support to the dockerfile and github actions
defenseunicorns/not-a-build-harness pull request #70
Opened 2023-05-19 22:49 UTC by zack-is-cool

Resolves #69

2023-05-20 00:10 UTC, zack-is-cool commented
Python took like 30 minutes to install on the arm container 🤔

2023-05-23 19:21 UTC, RothAndrew commented
@zack-is-cool As I was reviewing I ran across a much simpler example of doing this. Do you know whether this is something that would work for us? Or is the more complex version as it is here in the PR the only way?

https://github.com/docker/docs/blob/3275456427dbe05c249f3215cefa83ad27219918/build/ci/github-actions/examples.md

2023-05-23 19:32 UTC, RothAndrew requested changes
My only overall concern is that doing this removes the ability to easily switch python versions. However, I don't believe that's something that anyone using this image needs right now, so I'm good with it if it saves tons of time in the build process. If feedback comes out that different python versions need to be used we may need to reevaluate.

2023-05-23 19:32 UTC, RothAndrew commented on .github/workflows/release.yml
> +          docker buildx imagetools inspect ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ steps.meta.outputs.version }}
I'm not sure I'm understanding how it is tagging the different architectures. Can you explain? Does it do something like `X.Y.Z-amd64`?

2023-05-23 19:32 UTC, RothAndrew commented on .github/workflows/verify-build.yml
> +          touch "/tmp/digests/${digest#sha256:}"
Are we able to centralize a bunch of this to make it more DRY? It looks like there is a lot of duplication between this file and release.yml

2023-05-23 19:32 UTC, RothAndrew commented on .github/workflows/verify-build.yml
> +          outputs: type=image,name=${{ env.REGISTRY }}/${{ env.IMAGE_NAME }},push-by-digest=true,name-canonical=true,push=false
add no-cache, same comment as above.

2023-05-23 19:32 UTC, RothAndrew commented on .github/workflows/verify-build.yml
> +      - name: Export digest
Do we need to export the digests if we aren't uploading them?

2023-05-23 20:23 UTC, RothAndrew approved these changes

2023-05-23 20:36 UTC, merged